version: '3.8'

services:
  safot_frontend:
    image: bneibaruch/safot_frontend:${SAFOT_VERSION}
    container_name: safot_frontend
    ports:
      - "80:80"
    restart: no
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
