version: '3.8'
services:
  app:
    build:
      context: .
    env_file:
      - .env  # The base .env file for shared variables
    ports:
      - "${APP_PORT:-8000}:8000"  # Use default if APP_PORT is not defined
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
