services:
  safot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"  # Use default if APP_PORT is not defined
    depends_on:
      - safot-postgres
  safot-postgres:
    image: postgres:17-alpine  # Replace with your desired specific version, e.g., 15.4 or another stable release
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: